trigger:
- terraform_simple_module

pool: workload-selfhosted-agentpool

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- script: |
    cd dev
    terraform init
    terraform plan
    terraform apply -auto-approve
  displayName: 'Terraform Deploy'
